-- Script was generated by Devart Entity Developer, Version 6.12.1354.0
-- Script date 14-2-2022 17:06:21
-- Target Server: SQL Server
-- Server Version: 2016

-- 
-- Creating a table dbo.Companies 
-- 
CREATE TABLE dbo.Companies (
   Id UNIQUEIDENTIFIER NOT NULL,
   Name NVARCHAR(100) NOT NULL,
   CONSTRAINT PK_Companies PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table dbo.Customers 
-- 
CREATE TABLE dbo.Customers (
   Id INT NOT NULL IDENTITY,
   Name NVARCHAR(100) NOT NULL,
   ArchivedAtUtc DATETIME2,
   ArchivedBy NVARCHAR(100),
   CONSTRAINT PK_Customers PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table dbo.Stores 
-- 
CREATE TABLE dbo.Stores (
   Id UNIQUEIDENTIFIER NOT NULL,
   CONSTRAINT PK_Stores PRIMARY KEY (Id),
   CONSTRAINT FK_Stores_Companies FOREIGN KEY (Id) REFERENCES dbo.Companies (Id)
)
GO

-- 
-- Creating a table dbo.Suppliers 
-- 
CREATE TABLE dbo.Suppliers (
   Id UNIQUEIDENTIFIER NOT NULL,
   ContactFamilyName NVARCHAR(50) NOT NULL,
   ContactGivenName NVARCHAR(50),
   CONSTRAINT PK_Suppliers PRIMARY KEY (Id),
   CONSTRAINT FK_Suppliers_Companies FOREIGN KEY (Id) REFERENCES dbo.Companies (Id)
)
GO

