//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// PLEASE DO NOT MODIFY!
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace MyProject.Domain.Entities;

public partial class MyEntity {

    public MyEntity()
    {
        OnCreated();
    }

    public virtual Guid Id { get; set; }

    public virtual string Name { get; set; }

    public virtual DateTime CreatedAtUtc { get; set; }

    #region Extensibility Method Definitions

    partial void OnCreated();

    #endregion
}
